//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp1
    {
        public int EmpID { get; set; }
        public string Name { get; set; }
        public int Salary { get; set; }
    }
}
